GET http://localhost:5001/video/retrieve-podcasts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbXN0ZXN0dXNlciIsImlhdCI6MTU4Njc4Nzk1NiwiYWNjZXNzTGV2ZWwiOlsic3RhbmRhcmQtdXNlciJdLCJleHAiOjE1ODY4NzQzNTZ9.bM5csjNaATYX8QL3F7LMBy_bC7t19-nG9c2-TqT7_5U

###
GET http://localhost:5001/video/get-youtube-access-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbXN0ZXN0dXNlciIsImlhdCI6MTU4Njg5MzY3MCwiYWNjZXNzTGV2ZWwiOlsic3RhbmRhcmQtdXNlciIsImFkbWluIl0sImV4cCI6MTU4Njk4MDA3MH0.o60OhWP7QK837qaZ7mRkV0RSHYQRBqLeQ057M6xpWdU
audience: www.lightup-platform.com

{
    "pageName":"podcast"
}